name: build-kind-image
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/build-kind-image.yaml'
      - 'images/kind/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v2
      - name: install yq
        shell: bash
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.7.0/yq_linux_amd64 -O ./yq
          chmod +x ./yq
          sudo mv ./yq /usr/local/bin/yq
      - name: build
        shell: bash
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        run: |
          cd images/kind
          bash -x ./build.sh

          TAG=$(cat TAG)
          docker login quay.io -u $QUAY_USERNAME -p $QUAY_PASSWORD
          docker push quay.io/ekz-io/kind:$TAG
