name: build-kind-image
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/build-kind-image.yaml'
      - 'images/kind/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v2
      - name: build
        shell: bash
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        run: |
          cd images/kind
          TAG=$(cat VERSION)

          docker build -t quay.io/ekz-io/kind:$TAG .
          docker login quay.io -u $QUAY_USERNAME -p $QUAY_PASSWORD
          docker push quay.io/ekz-io/kind:$TAG
